In [ ]:
import pandas as pd

# Assuming 'historical_data' contains the NVIDIA DataFrame
if 'NVDA' in historical_data and not historical_data['NVDA'].empty:
    nvda_data = historical_data['NVDA']

    # Convert index to datetime if not already
    if not isinstance(nvda_data.index, pd.DatetimeIndex):
        nvda_data.index = pd.to_datetime(nvda_data.index)

    # Filter data around the user's specified date (assuming 2021-01-20 is meant)
    # Weekly data typically shows the last day of the week (e.g., Friday)
    # We'll look for entries in the vicinity of 2021-01-20.
    # A typical week containing 2021-01-20 would end on 2021-01-22 (Friday).
    start_date_search = '2021-01-15'
    end_date_search = '2021-01-25'

    print(f"NVIDIA (NVDA) weekly data around 2021-01-20 (looking between {start_date_search} and {end_date_search}):")
    relevant_nvda_data = nvda_data.loc[start_date_search:end_date_search]

    if not relevant_nvda_data.empty:
        display(relevant_nvda_data)
    else:
        print("No data found for NVDA in the specified range. Please check the date format or range.")
else:
    print("No historical data found for NVDA.")

NVIDIA (NVDA) weekly data around 2021-01-20 (looking between 2021-01-15 and 2021-01-25):

Price           Close       High        Low       Open      Volume
Ticker           NVDA       NVDA       NVDA       NVDA        NVDA
Date
2021-01-18  13.674047  13.959993  12.807982  12.979749  1069360000
2021-01-25  12.953323  13.789721  12.757873  13.743102  1286232000

In [ ]:
print("Earliest historical data for TSLA (Tesla Inc.):")
if 'TSLA' in historical_data and not historical_data['TSLA'].empty:
    display(historical_data['TSLA'].head(2))
else:
    print("No historical data found for TSLA.")

Earliest historical data for TSLA (Tesla Inc.):

Price      Close      High       Low      Open     Volume
Ticker      TSLA      TSLA      TSLA      TSLA       TSLA
Date
2010-06-28  1.28  2.028000  1.169333  1.266667  739680000
2010-07-05  1.16  1.333333  0.998667  1.333333  383259000

In [ ]:
print("Earliest historical data for AVGO (Broadcom Inc.):")
if 'AVGO' in historical_data and not historical_data['AVGO'].empty:
    display(historical_data['AVGO'].head(2))
else:
    print("No historical data found for AVGO.")

print("\nEarliest historical data for META (Meta Platforms Inc.):")
if 'META' in historical_data and not historical_data['META'].empty:
    display(historical_data['META'].head(2))
else:
    print("No historical data found for META.")

Earliest historical data for AVGO (Broadcom Inc.):

Price          Close      High       Low      Open     Volume
Ticker          AVGO      AVGO      AVGO      AVGO       AVGO
Date
2009-08-03  1.157385  1.191198  1.096099  1.162316  266521000
2009-08-10  1.169360  1.197538  1.091873  1.171474   79661000

Earliest historical data for META (Meta Platforms Inc.):

Price           Close       High        Low       Open     Volume
Ticker           META       META       META       META       META
Date
2012-05-14  37.964802  44.687839  37.736398  41.758303  573576400
2012-05-21  31.688644  36.405694  30.725374  36.276595  430966300

In [ ]:
from google.colab import files

consolidated_wide_file_name = 'sp500_historical_data_wide_format.csv'

try:
    files.download(consolidated_wide_file_name)
    print(f"Downloading {consolidated_wide_file_name}...")
except Exception as e:
    print(f"Could not download {consolidated_wide_file_name}: {e}")

Downloading sp500_historical_data_wide_format.csv...

### Subtask: Re-export Consolidated Historical Data to a Single Wide-Format CSV

**Reasoning**:
The user explicitly requested a wide-format CSV where each row corresponds to a date, and columns represent specific metrics (Open, High, Low, Close, Volume) for each company. To achieve this, I will iterate through the `historical_data` dictionary, rename the columns of each company's DataFrame to include its ticker symbol (e.g., 'Open' becomes 'Open_NVDA'), and then concatenate these modified DataFrames horizontally based on their 'Date' index. This will result in a single, wide DataFrame which will then be saved to a CSV file.

In [ ]:
import pandas as pd

# Prepare a list to hold modified DataFrames with ticker-specific column names
wide_format_dfs = []

for ticker_symbol, data_df in historical_data.items():
    # Create a copy to avoid modifying original DataFrames in historical_data
    df_copy = data_df.copy()

    # Rename columns to include the ticker symbol as a suffix
    # For example, 'Open' becomes 'Open_NVDA'
    df_copy.columns = [f"{col}_{ticker_symbol}" for col in df_copy.columns]

    wide_format_dfs.append(df_copy)

# Concatenate all DataFrames side-by-side, aligning on the 'Date' index
# The 'join="outer"' ensures all dates are included, filling missing values with NaN where data is unavailable.
consolidated_wide_df = pd.concat(wide_format_dfs, axis=1, join='outer')

# Define the file name for the new wide-format consolidated CSV
consolidated_wide_file_name = 'sp500_historical_data_wide_format.csv'

try:
    # Save the consolidated wide-format DataFrame to a single CSV file
    consolidated_wide_df.to_csv(consolidated_wide_file_name, index=True) # index=True to save the Date column
    print(f"Successfully saved all historical data to {consolidated_wide_file_name} in wide format.")
    print("First 5 rows of the new wide-format consolidated data:")
    display(consolidated_wide_df.head())
except Exception as e:
    print(f"Could not save consolidated data to CSV: {e}")

Successfully saved all historical data to sp500_historical_data_wide_format.csv in wide format.
First 5 rows of the new wide-format consolidated data:

,"('Close', 'NVDA')_NVDA","('High', 'NVDA')_NVDA","('Low', 'NVDA')_NVDA","('Open', 'NVDA')_NVDA","('Volume', 'NVDA')_NVDA","('Close', 'GOOGL')_GOOGL","('High', 'GOOGL')_GOOGL","('Low', 'GOOGL')_GOOGL","('Open', 'GOOGL')_GOOGL","('Volume', 'GOOGL')_GOOGL",...,"('Close', 'LIN')_LIN","('High', 'LIN')_LIN","('Low', 'LIN')_LIN","('Open', 'LIN')_LIN","('Volume', 'LIN')_LIN","('Close', 'PEP')_PEP","('High', 'PEP')_PEP","('Low', 'PEP')_PEP","('Open', 'PEP')_PEP","('Volume', 'PEP')_PEP"
Date,,,,,,,,,,,,,,,,,,,,,
2006-01-23,0.353364,0.357260,0.338083,0.340222,8.338800e+08,10.766747,10.928191,10.520113,10.917014,8.542769e+08,...,35.860821,36.223260,35.464192,35.970236,4193200.0,32.739727,32.784729,31.502142,32.424705,11001200.0
2006-01-30,0.336325,0.355273,0.330060,0.354891,2.129076e+09,9.476695,10.918505,9.253656,10.660941,3.511161e+09,...,34.910244,36.312124,34.841861,35.819758,7923500.0,32.255943,32.795980,31.952172,32.632843,20444300.0
2006-02-06,0.335408,0.349543,0.327539,0.335408,2.008044e+09,9.006275,9.684088,8.771065,9.570084,2.937484e+09,...,35.224819,35.983887,34.636715,35.047021,7013000.0,32.587845,32.711604,31.800290,32.199694,23147900.0
2006-02-13,0.362684,0.387516,0.332047,0.334339,4.779228e+09,9.158776,9.242975,8.390805,8.609623,3.314862e+09,...,36.934425,37.064357,34.773478,35.047016,6791700.0,33.144756,33.257264,32.239071,32.531592,16133900.0
2006-02-20,0.348856,0.362532,0.341521,0.361920,2.425356e+09,9.373620,9.468996,9.037323,9.101403,1.366556e+09,...,37.037006,37.604598,36.599346,37.091715,5519500.0,33.493519,33.696033,32.964732,33.032238,18438200.0

In [ ]:
from google.colab import files

consolidated_file_name = 'sp500_historical_data.csv'

try:
    files.download(consolidated_file_name)
    print(f"Downloading {consolidated_file_name}...")
except Exception as e:
    print(f"Could not download {consolidated_file_name}: {e}")

Downloading sp500_historical_data.csv...

In [ ]:
import pandas as pd

# Define the file name for the consolidated CSV
consolidated_file_name = 'sp500_historical_data.csv'

try:
    # Read the consolidated CSV file into a DataFrame
    consolidated_df_read = pd.read_csv(consolidated_file_name)
    print(f"Successfully read data from {consolidated_file_name}")
    print("First 5 rows of the consolidated data:")
    display(consolidated_df_read.head())
except Exception as e:
    print(f"Could not read consolidated data from CSV: {e}")

Successfully read data from sp500_historical_data.csv
First 5 rows of the consolidated data:

/tmp/ipython-input-1025115404.py:8: DtypeWarning: Columns (1,2,3,4,5,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251) have mixed types. Specify dtype option on import or set low_memory=False.
  consolidated_df_read = pd.read_csv(consolidated_file_name)

,Price,Close,High,Low,Open,Volume,Ticker,Close.1,High.1,Low.1,...,Close.48,High.48,Low.48,Open.48,Volume.48,Close.49,High.49,Low.49,Open.49,Volume.49
0,Ticker,NVDA,NVDA,NVDA,NVDA,NVDA,NaN,GOOGL,GOOGL,GOOGL,...,LIN,LIN,LIN,LIN,LIN,PEP,PEP,PEP,PEP,PEP
1,Date,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2006-01-23,0.353363573551178,0.35726011053112966,0.338082687058941,0.34022164830786866,833880000.0,NVDA,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2006-01-30,0.33632519841194153,0.3552734074817346,0.33006047925233245,0.3548910928558399,2129076000.0,NVDA,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2006-02-06,0.33540835976600647,0.34954318003208945,0.32753916004941336,0.33540835976600647,2008044000.0,NVDA,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Subtask: Export Historical Data to CSV

**Reasoning**:
To provide the historical data in an easily accessible format, I will iterate through the `historical_data` dictionary. For each ticker, I will save its corresponding DataFrame as a separate CSV file. The file names will be based on the ticker symbols for easy identification.

In [ ]:
# Define the directory to save CSV files (current directory)
output_directory = './'

# Loop through each ticker and its historical data
for ticker_symbol, data_df in historical_data.items():
    # Construct the file name using the ticker symbol
    file_name = f"{output_directory}{ticker_symbol}.csv"
    try:
        # Save the DataFrame to a CSV file
        data_df.to_csv(file_name, index=True) # index=True to save the Date column
        print(f"Successfully saved data for {ticker_symbol} to {file_name}")
    except Exception as e:
        print(f"Could not save data for {ticker_symbol} to CSV: {e}")

print("\nAll historical data has been exported to CSV files.")

Successfully saved data for NVDA to ./NVDA.csv
Successfully saved data for GOOGL to ./GOOGL.csv
Successfully saved data for GOOG to ./GOOG.csv
Successfully saved data for AAPL to ./AAPL.csv
Successfully saved data for MSFT to ./MSFT.csv
Successfully saved data for AMZN to ./AMZN.csv
Successfully saved data for AVGO to ./AVGO.csv
Successfully saved data for META to ./META.csv
Successfully saved data for TSLA to ./TSLA.csv
Successfully saved data for WMT to ./WMT.csv
Successfully saved data for LLY to ./LLY.csv
Successfully saved data for JPM to ./JPM.csv
Successfully saved data for V to ./V.csv
Successfully saved data for XOM to ./XOM.csv
Successfully saved data for JNJ to ./JNJ.csv
Successfully saved data for ORCL to ./ORCL.csv
Successfully saved data for MA to ./MA.csv
Successfully saved data for COST to ./COST.csv
Successfully saved data for MU to ./MU.csv
Successfully saved data for PLTR to ./PLTR.csv
Successfully saved data for BAC to ./BAC.csv
Successfully saved data for ABBV to ./ABBV.csv
Successfully saved data for AMD to ./AMD.csv
Successfully saved data for HD to ./HD.csv
Successfully saved data for NFLX to ./NFLX.csv
Successfully saved data for PG to ./PG.csv
Successfully saved data for CVX to ./CVX.csv
Successfully saved data for GE to ./GE.csv
Successfully saved data for KO to ./KO.csv
Successfully saved data for UNH to ./UNH.csv
Successfully saved data for CAT to ./CAT.csv
Successfully saved data for CSCO to ./CSCO.csv
Successfully saved data for MS to ./MS.csv
Successfully saved data for GS to ./GS.csv
Successfully saved data for LRCX to ./LRCX.csv
Successfully saved data for MRK to ./MRK.csv
Successfully saved data for IBM to ./IBM.csv
Successfully saved data for WFC to ./WFC.csv
Successfully saved data for RTX to ./RTX.csv
Successfully saved data for PM to ./PM.csv
Successfully saved data for AMAT to ./AMAT.csv
Successfully saved data for AXP to ./AXP.csv
Successfully saved data for TMO to ./TMO.csv
Successfully saved data for INTC to ./INTC.csv
Successfully saved data for MCD to ./MCD.csv
Successfully saved data for ABT to ./ABT.csv
Successfully saved data for CRM to ./CRM.csv
Successfully saved data for TMUS to ./TMUS.csv
Successfully saved data for LIN to ./LIN.csv
Successfully saved data for PEP to ./PEP.csv

All historical data has been exported to CSV files.

### Subtask: Export Consolidated Historical Data to a Single CSV

**Reasoning**:
To meet the user's request of having all historical data in one CSV file, I will first combine all individual DataFrames from the `historical_data` dictionary into a single large DataFrame. A 'Ticker' column will be added to identify the data origin for each row. Finally, this consolidated DataFrame will be saved as a single CSV file.

In [ ]:
import pandas as pd

# Initialize an empty list to hold dataframes with an added ticker column
all_dataframes = []

for ticker_symbol, df in historical_data.items():
    # Add a 'Ticker' column to each DataFrame before appending
    df_copy = df.copy()
    df_copy['Ticker'] = ticker_symbol
    all_dataframes.append(df_copy)

# Concatenate all DataFrames into a single DataFrame
consolidated_df = pd.concat(all_dataframes)

# Define the file name for the consolidated CSV
consolidated_file_name = 'sp500_historical_data.csv'

try:
    # Save the consolidated DataFrame to a single CSV file
    consolidated_df.to_csv(consolidated_file_name, index=True) # index=True to save the Date column
    print(f"Successfully saved all historical data to {consolidated_file_name}")
    print("First 5 rows of the consolidated data:")
    display(consolidated_df.head())
except Exception as e:
    print(f"Could not save consolidated data to CSV: {e}")

Successfully saved all historical data to sp500_historical_data.csv
First 5 rows of the consolidated data:

Price,Close,High,Low,Open,Volume,Ticker,Close,High,Low,Open,...,Close,High,Low,Open,Volume,Close,High,Low,Open,Volume
Ticker,NVDA,NVDA,NVDA,NVDA,NVDA,,GOOGL,GOOGL,GOOGL,GOOGL,...,LIN,LIN,LIN,LIN,LIN,PEP,PEP,PEP,PEP,PEP
Date,,,,,,,,,,,,,,,,,,,,,
2006-01-23,0.353364,0.357260,0.338083,0.340222,8.338800e+08,NVDA,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2006-01-30,0.336325,0.355273,0.330060,0.354891,2.129076e+09,NVDA,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2006-02-06,0.335408,0.349543,0.327539,0.335408,2.008044e+09,NVDA,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2006-02-13,0.362684,0.387516,0.332047,0.334339,4.779228e+09,NVDA,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2006-02-20,0.348856,0.362532,0.341521,0.361920,2.425356e+09,NVDA,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Task
Download and store historical weekly stock data for the top 50 S&P 500 companies for the last 20 years.

## Get S&P 500 Tickers

### Subtask:
Retrieve a list of the top 50 S&P 500 company stock tickers from a reliable source.

**Reasoning**:
First, I will import the pandas library to enable data manipulation, specifically for reading HTML tables. Then I will define the URL for the Wikipedia page containing the S&P 500 companies.

In [ ]:
import pandas as pd

# Define the URL for the Wikipedia page listing S&P 500 companies
url = 'https://en.wikipedia.org/wiki/List_of_S%26P_500_companies'

print("Pandas imported and URL defined.")

Pandas imported and URL defined.

**Reasoning**:
Now that the URL is defined, I will use `pd.read_html()` to extract all tables from the Wikipedia page, then identify the relevant table containing S&P 500 constituents.

In [ ]:
tables = pd.read_html(url)
# The S&P 500 constituents are typically in the first table.
sp500_table = tables[0]

print("HTML tables read and the first table extracted.")
print("First few rows of the extracted table:\n", sp500_table.head())

HTTPError: HTTP Error 403: Forbidden

**Reasoning**:
The previous code failed with an `HTTPError: 403 Forbidden`, indicating the website blocked the request. To fix this, I will use the `requests` library to fetch the HTML content with a `User-Agent` header, which often helps bypass such restrictions, and then pass the content to `pd.read_html()`.

In [ ]:
import requests

# Define a User-Agent header to mimic a web browser
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'}

# Fetch the HTML content using requests with the custom header
response = requests.get(url, headers=headers)

# Use pd.read_html to parse the content from the response
tables = pd.read_html(response.text)

# The S&P 500 constituents are typically in the first table.
sp500_table = tables[0]

print("HTML tables read and the first table extracted.")
print("First few rows of the extracted table:\n", sp500_table.head())

HTML tables read and the first table extracted.
First few rows of the extracted table:
   Symbol             Security             GICS Sector  \
0    MMM                   3M             Industrials
1    AOS          A. O. Smith             Industrials
2    ABT  Abbott Laboratories             Health Care
3   ABBV               AbbVie             Health Care
4    ACN            Accenture  Information Technology

                GICS Sub-Industry    Headquarters Location  Date added  \
0        Industrial Conglomerates    Saint Paul, Minnesota  1957-03-04
1               Building Products     Milwaukee, Wisconsin  2017-07-26
2           Health Care Equipment  North Chicago, Illinois  1957-03-04
3                   Biotechnology  North Chicago, Illinois  2012-12-31
4  IT Consulting & Other Services          Dublin, Ireland  2011-07-06

       CIK      Founded
0    66740         1902
1    91142         1916
2     1800         1888
3  1551152  2013 (1888)
4  1467373         1989

/tmp/ipython-input-4142551374.py:10: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(response.text)

**Reasoning**:
Now that the `sp500_table` is successfully extracted, I will extract the 'Symbol' column, which contains the stock ticker symbols, and then select the first 50 tickers to fulfill the subtask requirement.

In [ ]:
sp500_tickers = sp500_table['Symbol'].head(50).tolist()

print(f"Successfully extracted the first 50 S&P 500 tickers.\nNumber of tickers: {len(sp500_tickers)}")
print("First 10 tickers:", sp500_tickers[:10])

Successfully extracted the first 50 S&P 500 tickers.
Number of tickers: 50
First 10 tickers: ['MMM', 'AOS', 'ABT', 'ABBV', 'ACN', 'ADBE', 'AMD', 'AES', 'AFL', 'A']

## Define Date Range

### Subtask:
Calculate the start date (20 years ago from today) and the end date (today) for the data download.

**Reasoning**:
To calculate the start and end dates, I will import the necessary modules, get today's date, and then compute the date 20 years prior.

# Task
To define the date range for data download, import the `datetime` module, get today's date, and compute the date 20 years prior.

```python
from datetime import datetime, timedelta

# Get today's date
end_date = datetime.now()

# Calculate the start date (20 years ago from today)
start_date = end_date - timedelta(days=20 * 365) # Approximation for 20 years

print(f"End Date: {end_date.strftime('%Y-%m-%d')}")
print(f"Start Date (20 years ago): {start_date.strftime('%Y-%m-%d')}")
```

## Get S&P 500 Tickers by Market Cap

### Subtask:
Retrieve all S&P 500 company stock tickers from the previously extracted table. Then, for each ticker, fetch its market capitalization from a reliable source (e.g., yfinance). Finally, sort these companies by market capitalization in descending order and select the top 50.

**Reasoning**:
Before proceeding with fetching market capitalization, I need to ensure that the `yfinance` library is installed in the environment. I will use `!pip install yfinance` in a separate code block to achieve this.

In [ ]:
pip install yfinance

Requirement already satisfied: yfinance in /usr/local/lib/python3.12/dist-packages (0.2.66)
Requirement already satisfied: pandas>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.2.2)
Requirement already satisfied: numpy>=1.16.5 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.0.2)
Requirement already satisfied: requests>=2.31 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.32.4)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.12/dist-packages (from yfinance) (0.0.12)
Requirement already satisfied: platformdirs>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (4.5.1)
Requirement already satisfied: pytz>=2022.5 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2025.2)
Requirement already satisfied: frozendict>=2.3.4 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.4.7)
Requirement already satisfied: peewee>=3.16.2 in /usr/local/lib/python3.12/dist-packages (from yfinance) (3.19.0)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /usr/local/lib/python3.12/dist-packages (from yfinance) (4.13.5)
Requirement already satisfied: curl_cffi>=0.7 in /usr/local/lib/python3.12/dist-packages (from yfinance) (0.14.0)
Requirement already satisfied: protobuf>=3.19.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (5.29.5)
Requirement already satisfied: websockets>=13.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (15.0.1)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (2.8.1)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (4.15.0)
Requirement already satisfied: cffi>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from curl_cffi>=0.7->yfinance) (2.0.0)
Requirement already satisfied: certifi>=2024.2.2 in /usr/local/lib/python3.12/dist-packages (from curl_cffi>=0.7->yfinance) (2026.1.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3.0->yfinance) (2025.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (2.5.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.12.0->curl_cffi>=0.7->yfinance) (2.23)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)

**Reasoning**:
Now that the `yfinance` library is confirmed to be installed, I will proceed to import it, then iterate through all available S&P 500 tickers from the `sp500_table`, fetch their market capitalization using `yfinance`, store this information, and finally sort to get the top 50 by market cap as requested.

In [ ]:
import yfinance as yf

# Initialize an empty list to store ticker symbols and their market capitalizations
ticker_market_caps = []

# Iterate through each ticker symbol in the 'Symbol' column of the sp500_table DataFrame
for symbol in sp500_table['Symbol']:
    ticker = yf.Ticker(symbol)
    try:
        # Attempt to retrieve the 'marketCap' from the ticker's info attribute
        # Some tickers might not have marketCap directly available or might error out
        market_cap = ticker.info.get('marketCap', 0)
    except Exception:
        market_cap = 0 # Assign 0 if an error occurs during retrieval

    ticker_market_caps.append({'Symbol': symbol, 'MarketCap': market_cap})

# Convert the list of dictionaries into a pandas DataFrame
market_cap_df = pd.DataFrame(ticker_market_caps)

# Sort this DataFrame by the 'MarketCap' column in descending order
market_cap_df = market_cap_df.sort_values(by='MarketCap', ascending=False)

# Select the top 50 rows from the sorted DataFrame
top_50_sp500_tickers_by_market_cap = market_cap_df.head(50)['Symbol'].tolist()

print(f"Successfully retrieved and sorted S&P 500 tickers by market capitalization.")
print(f"Number of top 50 tickers by market cap: {len(top_50_sp500_tickers_by_market_cap)}")
print("First 10 tickers by market cap:", top_50_sp500_tickers_by_market_cap[:10])

Successfully retrieved and sorted S&P 500 tickers by market capitalization.
Number of top 50 tickers by market cap: 50
First 10 tickers by market cap: ['NVDA', 'GOOGL', 'GOOG', 'AAPL', 'MSFT', 'AMZN', 'AVGO', 'META', 'TSLA', 'WMT']

## Define Date Range

### Subtask:
Calculate the start date (20 years ago from today) and the end date (today) for the data download.

**Reasoning**:
To calculate the start and end dates as required by the subtask, I will import the `datetime` and `timedelta` classes, get the current date, calculate the date 20 years prior, and then print both dates in the specified format.

In [ ]:
from datetime import datetime, timedelta

# Get today's date
end_date = datetime.now()

# Calculate the start date (20 years ago from today)
start_date = end_date - timedelta(days=20 * 365) # Approximation for 20 years

print(f"End Date: {end_date.strftime('%Y-%m-%d')}")
print(f"Start Date (20 years ago): {start_date.strftime('%Y-%m-%d')}")

End Date: 2026-01-21
Start Date (20 years ago): 2006-01-26

## Download Historical Data

### Subtask:
Iterate through the top 50 tickers identified by market cap and download weekly historical data for each company within the defined 20-year date range using a library like `yfinance`.

**Reasoning**:
To download the historical data for the top 50 S&P 500 tickers, I will iterate through the `top_50_sp500_tickers_by_market_cap` list, use `yfinance` to download weekly data for the specified date range, and store it in a dictionary.

# Task
`run_code`

## Get S&P 500 Tickers by Market Cap

### Subtask:
Retrieve all S&P 500 company stock tickers from the previously extracted table. Then, for each ticker, fetch its market capitalization from a reliable source (e.g., yfinance). Finally, sort these companies by market capitalization in descending order and select the top 50.

## Download Weekly Historical Data

### Subtask:
Iterate through the top 50 tickers identified by market cap and download weekly historical data for each company within the defined 20-year date range using a library like `yfinance`.

**Reasoning**:
To download the historical data for the top 50 S&P 500 tickers, I will iterate through the `top_50_sp500_tickers_by_market_cap` list, use `yfinance` to download weekly data for the specified date range, and store it in a dictionary.

In [ ]:
import yfinance as yf

# Create an empty dictionary to store the historical data for each ticker
historical_data = {}

# Loop through each ticker symbol in the top 50 list
for ticker_symbol in top_50_sp500_tickers_by_market_cap:
    try:
        # Download weekly historical data
        data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')
        if not data.empty:
            historical_data[ticker_symbol] = data
            print(f"Successfully downloaded data for {ticker_symbol}")
        else:
            print(f"No data found for {ticker_symbol} in the specified range.")
    except Exception as e:
        print(f"Could not download data for {ticker_symbol}: {e}")

print(f"\nDownloaded weekly historical data for {len(historical_data)} out of {len(top_50_sp500_tickers_by_market_cap)} tickers.")

/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')
[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')
[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')

Successfully downloaded data for NVDA
Successfully downloaded data for GOOGL

[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')

Successfully downloaded data for GOOG

[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')

Successfully downloaded data for AAPL

[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')

Successfully downloaded data for MSFT

[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')
[*********************100%***********************]  1 of 1 completed

Successfully downloaded data for AMZN

/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')
[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')

Successfully downloaded data for AVGO
Successfully downloaded data for META

[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')

Successfully downloaded data for TSLA

[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')

Successfully downloaded data for WMT

[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')

Successfully downloaded data for LLY

[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')

Successfully downloaded data for JPM

[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')

Successfully downloaded data for V

[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')

Successfully downloaded data for XOM

[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')
[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')

Successfully downloaded data for JNJ
Successfully downloaded data for ORCL

[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')

Successfully downloaded data for MA

[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')

Successfully downloaded data for COST

[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')
[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')

Successfully downloaded data for MU
Successfully downloaded data for PLTR

[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')
[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')

Successfully downloaded data for BAC
Successfully downloaded data for ABBV

[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')

Successfully downloaded data for AMD

[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')
[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')

Successfully downloaded data for HD
Successfully downloaded data for NFLX

[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')

Successfully downloaded data for PG

[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')

Successfully downloaded data for CVX

[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')

Successfully downloaded data for GE

[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')

Successfully downloaded data for KO

[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')

Successfully downloaded data for UNH

[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')
[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')

Successfully downloaded data for CAT
Successfully downloaded data for CSCO

[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')

Successfully downloaded data for MS

[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')
[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')

Successfully downloaded data for GS
Successfully downloaded data for LRCX

[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')

Successfully downloaded data for MRK

[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')

Successfully downloaded data for IBM

[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')

Successfully downloaded data for WFC

[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')
[*********************100%***********************]  1 of 1 completed

Successfully downloaded data for RTX

/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')

Successfully downloaded data for PM

[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')

Successfully downloaded data for AMAT

[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')

Successfully downloaded data for AXP

[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')

Successfully downloaded data for TMO

[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')

Successfully downloaded data for INTC

[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')

Successfully downloaded data for MCD

[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')
[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')

Successfully downloaded data for ABT
Successfully downloaded data for CRM

[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')

Successfully downloaded data for TMUS

[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')

Successfully downloaded data for LIN

[*********************100%***********************]  1 of 1 completed

Successfully downloaded data for PEP

Downloaded weekly historical data for 50 out of 50 tickers.

**Reasoning**:
The previous code block successfully downloaded the historical data for all 50 tickers. The warnings encountered are `FutureWarning` messages and do not indicate an error preventing the successful completion of the subtask. Therefore, no modifications are needed, and this subtask is now complete.

In [ ]:
import yfinance as yf

# Create an empty dictionary to store the historical data for each ticker
historical_data = {}

# Loop through each ticker symbol in the top 50 list
for ticker_symbol in top_50_sp500_tickers_by_market_cap:
    try:
        # Download weekly historical data
        data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')
        if not data.empty:
            historical_data[ticker_symbol] = data
            print(f"Successfully downloaded data for {ticker_symbol}")
        else:
            print(f"No data found for {ticker_symbol} in the specified range.")
    except Exception as e:
        print(f"Could not download data for {ticker_symbol}: {e}")

print(f"\nDownloaded weekly historical data for {len(historical_data)} out of {len(top_50_sp500_tickers_by_market_cap)} tickers.")

/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')
[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')
[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')

Successfully downloaded data for NVDA
Successfully downloaded data for GOOGL

[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')
[*********************100%***********************]  1 of 1 completed

Successfully downloaded data for GOOG

/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')
[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')

Successfully downloaded data for AAPL
Successfully downloaded data for MSFT

[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')
[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')

Successfully downloaded data for AMZN
Successfully downloaded data for AVGO

[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')
[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')

Successfully downloaded data for META
Successfully downloaded data for TSLA

[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')

Successfully downloaded data for WMT

[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')

Successfully downloaded data for LLY

[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')
[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')

Successfully downloaded data for JPM
Successfully downloaded data for V

[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')

Successfully downloaded data for XOM

[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')
[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')

Successfully downloaded data for JNJ
Successfully downloaded data for ORCL

[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')
[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')

Successfully downloaded data for MA
Successfully downloaded data for COST

[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')
[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')

Successfully downloaded data for MU
Successfully downloaded data for PLTR

[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')
[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')

Successfully downloaded data for BAC
Successfully downloaded data for ABBV

[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')
[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')

Successfully downloaded data for AMD
Successfully downloaded data for HD

[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')

Successfully downloaded data for NFLX

[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')

Successfully downloaded data for PG

[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')

Successfully downloaded data for CVX

[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')

Successfully downloaded data for GE

[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')
[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')

Successfully downloaded data for KO
Successfully downloaded data for UNH

[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')
[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')

Successfully downloaded data for CAT
Successfully downloaded data for CSCO

[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')
[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')

Successfully downloaded data for MS
Successfully downloaded data for GS

[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')

Successfully downloaded data for LRCX

[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')

Successfully downloaded data for MRK

[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')

Successfully downloaded data for IBM

[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')

Successfully downloaded data for WFC

[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')
[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')

Successfully downloaded data for RTX
Successfully downloaded data for PM

[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')
[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')

Successfully downloaded data for AMAT
Successfully downloaded data for AXP

[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')
[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')

Successfully downloaded data for TMO
Successfully downloaded data for INTC

[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')
[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')

Successfully downloaded data for MCD
Successfully downloaded data for ABT

[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')
[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')

Successfully downloaded data for CRM
Successfully downloaded data for TMUS

[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-3571685691.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk')
[*********************100%***********************]  1 of 1 completed

Successfully downloaded data for LIN
Successfully downloaded data for PEP

Downloaded weekly historical data for 50 out of 50 tickers.

**Reasoning**:
Now that the historical data for the top 50 S&P 500 tickers has been successfully downloaded into the `historical_data` dictionary, the next logical step is to store this data in a persistent format. A common and efficient way to store time-series data is in a database. I will use SQLite for this purpose, as it is file-based and doesn't require a separate server.

In [ ]:
import sqlite3

# Define the database file name
db_name = 'sp500_historical_data.db'

# Connect to the SQLite database (it will be created if it doesn't exist)
conn = sqlite3.connect(db_name)

# Iterate through the historical_data dictionary and store each DataFrame in a separate table
for ticker_symbol, data_df in historical_data.items():
    # Table names cannot start with numbers and should be valid identifiers.
    # Replace any invalid characters in the ticker symbol to create a valid table name.
    table_name = ticker_symbol.replace('.', '_').replace('^', '_')
    try:
        # Write the DataFrame to a SQL table. If the table already exists, it will be replaced.
        data_df.to_sql(table_name, conn, if_exists='replace', index=True)
        print(f"Successfully stored data for {ticker_symbol} in table {table_name}")
    except Exception as e:
        print(f"Could not store data for {ticker_symbol}: {e}")

# Close the database connection
conn.close()

print(f"\nAll historical data stored in {db_name}")

Successfully stored data for NVDA in table NVDA
Successfully stored data for GOOGL in table GOOGL
Successfully stored data for GOOG in table GOOG
Successfully stored data for AAPL in table AAPL
Successfully stored data for MSFT in table MSFT
Successfully stored data for AMZN in table AMZN
Successfully stored data for AVGO in table AVGO
Successfully stored data for META in table META
Successfully stored data for TSLA in table TSLA
Successfully stored data for WMT in table WMT
Successfully stored data for LLY in table LLY
Successfully stored data for JPM in table JPM
Successfully stored data for V in table V
Successfully stored data for XOM in table XOM
Successfully stored data for JNJ in table JNJ
Successfully stored data for ORCL in table ORCL
Successfully stored data for MA in table MA
Successfully stored data for COST in table COST
Successfully stored data for MU in table MU
Successfully stored data for PLTR in table PLTR
Successfully stored data for BAC in table BAC
Successfully stored data for ABBV in table ABBV
Successfully stored data for AMD in table AMD
Successfully stored data for HD in table HD
Successfully stored data for NFLX in table NFLX
Successfully stored data for PG in table PG
Successfully stored data for CVX in table CVX
Successfully stored data for GE in table GE
Successfully stored data for KO in table KO
Successfully stored data for UNH in table UNH
Successfully stored data for CAT in table CAT
Successfully stored data for CSCO in table CSCO
Successfully stored data for MS in table MS
Successfully stored data for GS in table GS
Successfully stored data for LRCX in table LRCX
Successfully stored data for MRK in table MRK
Successfully stored data for IBM in table IBM
Successfully stored data for WFC in table WFC
Successfully stored data for RTX in table RTX
Successfully stored data for PM in table PM
Successfully stored data for AMAT in table AMAT
Successfully stored data for AXP in table AXP
Successfully stored data for TMO in table TMO
Successfully stored data for INTC in table INTC
Successfully stored data for MCD in table MCD
Successfully stored data for ABT in table ABT
Successfully stored data for CRM in table CRM
Successfully stored data for TMUS in table TMUS
Successfully stored data for LIN in table LIN
Successfully stored data for PEP in table PEP

All historical data stored in sp500_historical_data.db

## Final Task

### Subtask:
Confirm that the weekly historical data for the top 50 S&P 500 companies by market capitalization has been successfully downloaded and stored, and provide instructions on how to access it.

## Summary:

### Q&A
Yes, the weekly historical data for the top 50 S&P 500 companies by market capitalization has been successfully downloaded and stored.

To access the data, you can connect to the SQLite database named `sp500_historical_data.db`. Within this database, each company's historical data is stored in a separate table. The table names correspond to the company's ticker symbol, with characters like '.' and '^' replaced by '_' to ensure valid table names (e.g., 'BRK.B' would be 'BRK_B'). You can use standard SQL queries to retrieve data from these tables.

### Data Analysis Key Findings
*   The top 50 S&P 500 tickers by market capitalization were successfully identified and made available, having been pre-calculated.
*   Weekly historical data for all 50 identified tickers was successfully downloaded for a 20-year range using `yfinance` with an `interval='1wk'`.
*   The downloaded data was persistently stored in an SQLite database named `sp500_historical_data.db`.
*   Each ticker's historical data is stored in its own dedicated table within the database; for instance, a ticker like `BRK.B` would have its data stored in a table named `BRK_B`.
*   All 50 tickers' data frames were successfully written to their respective tables in the database.
*   `FutureWarning` messages were observed during the download process regarding `yf.download()`'s `auto_adjust` parameter, but these did not hinder the successful retrieval of data.

### Insights or Next Steps
*   The structured database of historical weekly data for the top 50 S&P 500 companies is now ready for various financial analyses, including trend analysis, volatility studies, or backtesting trading strategies.
*   Consider automating the database connection and query process in future analysis steps to streamline data retrieval for specific tickers or timeframes.

### Listing First Few Rows of All CSV Files in Current Directory

In [ ]:
import os
import pandas as pd

# Get current working directory
current_directory = os.getcwd()

# List all files in the current directory
files_in_directory = os.listdir(current_directory)

# Filter for CSV files
csv_files = [f for f in files_in_directory if f.endswith('.csv')]

print(f"Found {len(csv_files)} CSV files in the current directory:")
for csv_file in csv_files:
    print(f"\n--- Displaying first 5 rows of {csv_file} ---")
    try:
        # Attempt to read the CSV with default settings (utf-8)
        df = pd.read_csv(csv_file)
        display(df.head())
    except UnicodeDecodeError as e:
        print(f"Could not read {csv_file} with default (utf-8) encoding. Trying 'latin1'. Error: {e}")
        try:
            # Try 'latin1' encoding
            df = pd.read_csv(csv_file, encoding='latin1')
            display(df.head())
        except UnicodeDecodeError as e_latin1:
            print(f"Could not read {csv_file} with 'latin1' encoding. Trying 'cp1252'. Error: {e_latin1}")
            try:
                # Try 'cp1252' encoding (Windows-1252)
                df = pd.read_csv(csv_file, encoding='cp1252')
                display(df.head())
            except Exception as e_cp1252:
                print(f"Could not read {csv_file} with 'cp1252' encoding either. Last attempt: 'utf-8' with errors='replace'. Error: {e_cp1252}")
                try:
                    df = pd.read_csv(csv_file, encoding='utf-8', errors='replace')
                    display(df.head())
                except Exception as e_final:
                    print(f"Failed to read {csv_file} even with 'utf-8' and errors='replace'. Error: {e_final}")
    except Exception as e:
        # Catch other potential errors during file reading (e.g., file not found, permission issues)
        print(f"An unexpected error occurred while reading {csv_file}: {e}")

Found 3 CSV files in the current directory:

--- Displaying first 5 rows of sp500_headlines_2008_2024 2.csv ---

                                               Title        Date       CP
0   JPMorgan Predicts 2008 Will Be "Nothing But Net"  2008-01-02  1447.16
1  Dow Tallies Biggest First-session-of-year Poin...  2008-01-02  1447.16
2                   2008 predictions for the S&P 500  2008-01-02  1447.16
3  U.S. Stocks Higher After Economic Data, Monsan...  2008-01-03  1447.16
4  U.S. Stocks Climb As Hopes Increase For More F...  2008-01-07  1416.18

--- Displaying first 5 rows of financial_sentiment_lexicon 2.csv ---

            Word_or_Phrase  Sentiment_Score
0                  bullish             -0.9
1  outperform expectations             -0.9
2        miss expectations             -0.9
3                   buyout             -0.9
4         hostile takeover             -0.9

--- Displaying first 5 rows of all-data.csv ---
Could not read all-data.csv with default (utf-8) encoding. Trying 'latin1'. Error: 'utf-8' codec can't decode byte 0xc6 in position 2582: invalid continuation byte

,neutral,"According to Gran , the company has no plans to move all production to Russia , although that is where the company is growing ."
0,neutral,Technopolis plans to develop in stages an area...
1,negative,The international electronic industry company ...
2,positive,With the new production plant the company woul...
3,positive,According to the company 's updated strategy f...
4,positive,FINANCING OF ASPOCOMP 'S GROWTH Aspocomp is ag...

In [ ]:
import pandas as pd

# Load and inspect stock_data_Complete.json
print("\n--- Inspecting /content/stock_data_Complete.json ---")
try:
    df_stock_json = pd.read_json('/content/stock_data_Complete.json')
    print("First 5 rows of stock_data_Complete.json:")
    display(df_stock_json.head())
    print("Info of stock_data_Complete.json:")
    df_stock_json.info()
except Exception as e:
    print(f"Could not load stock_data_Complete.json: {e}")

--- Inspecting /content/stock_data_Complete.json ---
First 5 rows of stock_data_Complete.json:

,Unnamed: 0,links,symbol,company,Title,Text,Publishdate,Change
0,0,https://www.cnbc.com/2023/06/05/stocks-making-...,MMM,3M,Stocks making the biggest moves midday: Palo A...,A view of the exterior of the new Dutch head o...,2023-06-05,-2.441467
1,1,https://www.cnbc.com/2022/07/26/3m-will-spin-o...,MMM,3M,3M will spin off its health-care business into...,3M announced Tuesday it will spin off its heal...,2022-07-26,-2.307693
2,2,https://www.cnbc.com/2023/01/24/stocks-making-...,MMM,3M,"Stocks making the biggest moves midday: 3M, Pa...",A woman walks near a Bed Bath & Beyond branch ...,2023-01-24,-0.869568
3,3,https://www.cnbc.com/2023/01/24/3m-to-cut-2500...,MMM,3M,"3M to cut 2,500 jobs as demand weakens, profit...",An employee unboxes N95 masks as part of a gov...,2023-01-24,-0.869568
4,4,https://www.cnbc.com/2022/08/26/3m-combat-earp...,MMM,3M,"3M combat earplug lawsuits to proceed, judge r...","3M must face more than 230,000 lawsuits accusi...",2022-08-26,-12.123749

Info of stock_data_Complete.json:
<class 'pandas.core.frame.DataFrame'>
Index: 4589 entries, 0 to 4588
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   4589 non-null   int64
 1   links        4589 non-null   object
 2   symbol       4589 non-null   object
 3   company      4589 non-null   object
 4   Title        4589 non-null   object
 5   Text         4581 non-null   object
 6   Publishdate  4589 non-null   object
 7   Change       4528 non-null   float64
dtypes: float64(1), int64(1), object(6)
memory usage: 322.7+ KB

In [ ]:
import pandas as pd

# Load and inspect all-data.csv
print("\n--- Inspecting /content/all-data.csv ---")
try:
    df_all_data = pd.read_csv('/content/all-data.csv')
    print("First 5 rows of all-data.csv:")
    display(df_all_data.head())
    print("Info of all-data.csv:")
    df_all_data.info()
except UnicodeDecodeError as e:
    print(f"Could not read /content/all-data.csv with default (utf-8) encoding. Trying 'latin1'. Error: {e}")
    try:
        df_all_data = pd.read_csv('/content/all-data.csv', encoding='latin1')
        display(df_all_data.head())
        df_all_data.info()
    except UnicodeDecodeError as e_latin1:
        print(f"Could not read /content/all-data.csv with 'latin1' encoding. Trying 'cp1252'. Error: {e_latin1}")
        try:
            df_all_data = pd.read_csv('/content/all-data.csv', encoding='cp1252')
            display(df_all_data.head())
            df_all_data.info()
        except Exception as e_cp1252:
            print(f"Could not read /content/all-data.csv with 'cp1252' encoding either. Last attempt: 'utf-8' with errors='replace'. Error: {e_cp1252}")
            try:
                df_all_data = pd.read_csv('/content/all-data.csv', encoding='utf-8', errors='replace')
                display(df_all_data.head())
                df_all_data.info()
            except Exception as e_final:
                print(f"Failed to read /content/all-data.csv even with 'utf-8' and errors='replace'. Error: {e_final}")
except Exception as e:
    print(f"An unexpected error occurred while reading /content/all-data.csv: {e}")

--- Inspecting /content/all-data.csv ---
Could not read /content/all-data.csv with default (utf-8) encoding. Trying 'latin1'. Error: 'utf-8' codec can't decode byte 0xc6 in position 2582: invalid continuation byte

,neutral,"According to Gran , the company has no plans to move all production to Russia , although that is where the company is growing ."
0,neutral,Technopolis plans to develop in stages an area...
1,negative,The international electronic industry company ...
2,positive,With the new production plant the company woul...
3,positive,According to the company 's updated strategy f...
4,positive,FINANCING OF ASPOCOMP 'S GROWTH Aspocomp is ag...

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4845 entries, 0 to 4844
Data columns (total 2 columns):
 #   Column                                                                                                                           Non-Null Count  Dtype
---  ------                                                                                                                           --------------  -----
 0   neutral                                                                                                                          4845 non-null   object
 1   According to Gran , the company has no plans to move all production to Russia , although that is where the company is growing .  4845 non-null   object
dtypes: object(2)
memory usage: 75.8+ KB

In [ ]:
import pandas as pd

# Explicitly load the financial sentiment lexicon
# This ensures df_lexicon is available for sentiment calculation
try:
    df_lexicon = pd.read_csv('/content/financial_sentiment_lexicon 2.csv')
    print("Successfully loaded financial_sentiment_lexicon 2.csv into df_lexicon.")
    print("First 5 rows of df_lexicon:")
    display(df_lexicon.head())
except Exception as e:
    print(f"Could not load financial_sentiment_lexicon 2.csv: {e}")

Successfully loaded financial_sentiment_lexicon 2.csv into df_lexicon.
First 5 rows of df_lexicon:

            Word_or_Phrase  Sentiment_Score
0                  bullish             -0.9
1  outperform expectations             -0.9
2        miss expectations             -0.9
3                   buyout             -0.9
4         hostile takeover             -0.9

### Consolidating Datasets and Adding Sentiment Scores

**Reasoning**:
1. I'll rename columns in `df_stock_json` for better clarity (`symbol` to `Ticker`, `Publishdate` to `Date`, `Title` to `News_Title`, `Text` to `News_Text`).
2. Convert the `Date` column to datetime objects.
3. The `financial_sentiment_lexicon 2.csv` will be converted into a dictionary for efficient lookup.
4. I will create a function `calculate_sentiment` that takes text and the lexicon, tokenizes the text, and calculates an average sentiment score based on matching words.
5. Apply this function to the `News_Title` and `News_Text` columns of the consolidated DataFrame to get sentiment scores.

In [ ]:
import re
from nltk.tokenize import word_tokenize
import nltk
nltk.download('punkt')
nltk.download('punkt_tab') # Add this line to download the missing resource

# --- Step 1: Prepare df_stock_json ---
# Make a copy to avoid modifying the original DataFrame if it's used elsewhere
df_consolidated = df_stock_json.copy()

# Rename columns for clarity and consistency
df_consolidated = df_consolidated.rename(columns={
    'symbol': 'Ticker',
    'Publishdate': 'Date',
    'Title': 'News_Title',
    'Text': 'News_Text'
})

# Convert 'Date' column to datetime objects
df_consolidated['Date'] = pd.to_datetime(df_consolidated['Date'])

# --- Step 2: Prepare the Sentiment Lexicon ---
# Convert the lexicon DataFrame to a dictionary for faster lookups
sentiment_lexicon_dict = dict(zip(df_lexicon['Word_or_Phrase'], df_lexicon['Sentiment_Score']))

# --- Step 3: Define Sentiment Calculation Function ---
def calculate_sentiment(text, lexicon_dict):
    if pd.isna(text) or not isinstance(text, str):
        return 0.0 # Return 0 for missing or non-string text

    # Convert text to lowercase and tokenize
    words = word_tokenize(text.lower())

    # Remove punctuation and non-alphabetic words (optional, but good for lexicon matching)
    words = [re.sub(r'[^a-z]', '', word) for word in words if word.isalpha()]

    # Get scores for words present in the lexicon
    scores = [lexicon_dict[word] for word in words if word in lexicon_dict]

    # Return the average score, or 0 if no matching words are found
    return sum(scores) / len(scores) if scores else 0.0

# --- Step 4: Apply Sentiment Scoring ---
# Calculate sentiment for News_Title
df_consolidated['Title_Sentiment'] = df_consolidated['News_Title'].apply(lambda x: calculate_sentiment(x, sentiment_lexicon_dict))

# Calculate sentiment for News_Text
df_consolidated['Text_Sentiment'] = df_consolidated['News_Text'].apply(lambda x: calculate_sentiment(x, sentiment_lexicon_dict))

# Optionally, create a combined sentiment score (e.g., average of title and text sentiment)
df_consolidated['Combined_Sentiment'] = (df_consolidated['Title_Sentiment'] + df_consolidated['Text_Sentiment']) / 2

# --- Display the first few rows of the consolidated dataset ---
print("\nFirst 5 rows of the consolidated dataset with sentiment scores:")
display(df_consolidated.head())

print("\nInfo of the consolidated dataset:")
df_consolidated.info()

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

First 5 rows of the consolidated dataset with sentiment scores:

,Unnamed: 0,links,Ticker,company,News_Title,News_Text,Date,Change,Title_Sentiment,Text_Sentiment,Combined_Sentiment
0,0,https://www.cnbc.com/2023/06/05/stocks-making-...,MMM,3M,Stocks making the biggest moves midday: Palo A...,A view of the exterior of the new Dutch head o...,2023-06-05,-2.441467,0.0,-0.640000,-0.320000
1,1,https://www.cnbc.com/2022/07/26/3m-will-spin-o...,MMM,3M,3M will spin off its health-care business into...,3M announced Tuesday it will spin off its heal...,2022-07-26,-2.307693,0.0,-0.600000,-0.300000
2,2,https://www.cnbc.com/2023/01/24/stocks-making-...,MMM,3M,"Stocks making the biggest moves midday: 3M, Pa...",A woman walks near a Bed Bath & Beyond branch ...,2023-01-24,-0.869568,0.0,-0.596429,-0.298214
3,3,https://www.cnbc.com/2023/01/24/3m-to-cut-2500...,MMM,3M,"3M to cut 2,500 jobs as demand weakens, profit...",An employee unboxes N95 masks as part of a gov...,2023-01-24,-0.869568,-0.7,-0.650000,-0.675000
4,4,https://www.cnbc.com/2022/08/26/3m-combat-earp...,MMM,3M,"3M combat earplug lawsuits to proceed, judge r...","3M must face more than 230,000 lawsuits accusi...",2022-08-26,-12.123749,-0.6,-0.550000,-0.575000

Info of the consolidated dataset:
<class 'pandas.core.frame.DataFrame'>
Index: 4589 entries, 0 to 4588
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          4589 non-null   int64
 1   links               4589 non-null   object
 2   Ticker              4589 non-null   object
 3   company             4589 non-null   object
 4   News_Title          4589 non-null   object
 5   News_Text           4581 non-null   object
 6   Date                4589 non-null   datetime64[ns]
 7   Change              4528 non-null   float64
 8   Title_Sentiment     4589 non-null   float64
 9   Text_Sentiment      4589 non-null   float64
 10  Combined_Sentiment  4589 non-null   float64
dtypes: datetime64[ns](1), float64(4), int64(1), object(5)
memory usage: 430.2+ KB

In [ ]:
import pandas as pd

# Load and inspect sp500_headlines_2008_2024 2.csv
print("\n--- Inspecting /content/sp500_headlines_2008_2024 2.csv ---")
try:
    df_headlines = pd.read_csv('/content/sp500_headlines_2008_2024 2.csv')
    print("First 5 rows of sp500_headlines_2008_2024 2.csv:")
    display(df_headlines.head())
    print("Info of sp500_headlines_2008_2024 2.csv:")
    df_headlines.info()
except Exception as e:
    print(f"Could not load sp500_headlines_2008_2024 2.csv: {e}")

--- Inspecting /content/sp500_headlines_2008_2024 2.csv ---
First 5 rows of sp500_headlines_2008_2024 2.csv:

                                               Title        Date       CP
0   JPMorgan Predicts 2008 Will Be "Nothing But Net"  2008-01-02  1447.16
1  Dow Tallies Biggest First-session-of-year Poin...  2008-01-02  1447.16
2                   2008 predictions for the S&P 500  2008-01-02  1447.16
3  U.S. Stocks Higher After Economic Data, Monsan...  2008-01-03  1447.16
4  U.S. Stocks Climb As Hopes Increase For More F...  2008-01-07  1416.18

Info of sp500_headlines_2008_2024 2.csv:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19127 entries, 0 to 19126
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Title   19127 non-null  object
 1   Date    19127 non-null  object
 2   CP      19127 non-null  float64
dtypes: float64(1), object(2)
memory usage: 448.4+ KB

### Calculating Sentiment for General S&P 500 Headlines

In [ ]:
# Make a copy to avoid modifying the original df_headlines if it's used elsewhere
df_general_headlines_sentiment = df_headlines.copy()

# Convert 'Date' column to datetime objects
df_general_headlines_sentiment['Date'] = pd.to_datetime(df_general_headlines_sentiment['Date'])

# Calculate sentiment for the 'Title' column
df_general_headlines_sentiment['Headline_Sentiment'] = df_general_headlines_sentiment['Title'].apply(lambda x: calculate_sentiment(x, sentiment_lexicon_dict))

print("\nFirst 5 rows of the general S&P 500 headlines with sentiment scores:")
display(df_general_headlines_sentiment.head())

print("\nInfo of the general S&P 500 headlines with sentiment scores:")
df_general_headlines_sentiment.info()

First 5 rows of the general S&P 500 headlines with sentiment scores:

,Title,Date,CP,Headline_Sentiment
0,"JPMorgan Predicts 2008 Will Be ""Nothing But Net""",2008-01-02,1447.16,0.0
1,Dow Tallies Biggest First-session-of-year Poin...,2008-01-02,1447.16,0.0
2,2008 predictions for the S&P 500,2008-01-02,1447.16,0.0
3,"U.S. Stocks Higher After Economic Data, Monsan...",2008-01-03,1447.16,0.0
4,U.S. Stocks Climb As Hopes Increase For More F...,2008-01-07,1416.18,0.0

Info of the general S&P 500 headlines with sentiment scores:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19127 entries, 0 to 19126
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Title               19127 non-null  object
 1   Date                19127 non-null  datetime64[ns]
 2   CP                  19127 non-null  float64
 3   Headline_Sentiment  19127 non-null  float64
dtypes: datetime64[ns](1), float64(2), object(1)
memory usage: 597.8+ KB

### Download General S&P 500 Headlines with Sentiment Scores

In [ ]:
from google.colab import files

output_file_name = 'general_sp500_headlines_with_sentiment.csv'

try:
    df_general_headlines_sentiment.to_csv(output_file_name, index=False)
    print(f"Successfully saved '{output_file_name}'")
    files.download(output_file_name)
    print(f"Downloading {output_file_name}...")
except Exception as e:
    print(f"Could not save or download {output_file_name}: {e}")

Successfully saved 'general_sp500_headlines_with_sentiment.csv'

Downloading general_sp500_headlines_with_sentiment.csv...

### Inspecting the new `combined.csv` file

In [ ]:
import pandas as pd

file_name = '/content/combined.csv'

try:
    df_combined = pd.read_csv(file_name)
    print(f"Successfully loaded {file_name}")
    print("First 5 rows of the combined data:")
    display(df_combined.head())
    print("Info of the combined data:")
    df_combined.info()
except Exception as e:
    print(f"Could not load {file_name}: {e}")

Successfully loaded /content/combined.csv
First 5 rows of the combined data:

,ticker,headline,date,eventRet,Close
0,AMZN,Whole Foods (WFMI) -5.2% following a downgrade...,2011-05-02,0.017650,10.059500
1,NFLX,Netflix (NFLX +1.1%) shares post early gains a...,2011-05-02,-0.012912,33.884285
2,MSFT,The likely winners in Microsoft's (MSFT -1.4%)...,2011-05-10,-0.019817,20.120024
3,MSFT,Microsoft (MSFT -1.2%) and Skype signed their ...,2011-05-10,-0.019817,20.120024
4,MSFT,NaN,2011-05-10,-0.019817,20.120024

Info of the combined data:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2768 entries, 0 to 2767
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ticker    2768 non-null   object
 1   headline  2759 non-null   object
 2   date      2768 non-null   object
 3   eventRet  2768 non-null   float64
 4   Close     2768 non-null   float64
dtypes: float64(2), object(3)
memory usage: 108.3+ KB

In [ ]:
display(df_combined.head())

,ticker,headline,date,eventRet,Close
0,AMZN,Whole Foods (WFMI) -5.2% following a downgrade...,2011-05-02,0.017650,10.059500
1,NFLX,Netflix (NFLX +1.1%) shares post early gains a...,2011-05-02,-0.012912,33.884285
2,MSFT,The likely winners in Microsoft's (MSFT -1.4%)...,2011-05-10,-0.019817,20.120024
3,MSFT,Microsoft (MSFT -1.2%) and Skype signed their ...,2011-05-10,-0.019817,20.120024
4,MSFT,NaN,2011-05-10,-0.019817,20.120024

### Calculating Sentiment for Company-Specific Headlines from `combined.csv`

In [ ]:
# Make a copy to avoid modifying the original df_combined if it's used elsewhere
df_company_headlines_sentiment = df_combined.copy()

# Rename columns for consistency, if necessary (assuming 'ticker' and 'headline' are already good)
df_company_headlines_sentiment = df_company_headlines_sentiment.rename(columns={
    'headline': 'News_Title' # Aligning with previous sentiment calculation for consistency
})

# Convert 'date' column to datetime objects
df_company_headlines_sentiment['date'] = pd.to_datetime(df_company_headlines_sentiment['date'])

# Calculate sentiment for the 'News_Title' (formerly 'headline') column
df_company_headlines_sentiment['Title_Sentiment'] = df_company_headlines_sentiment['News_Title'].apply(lambda x: calculate_sentiment(x, sentiment_lexicon_dict))

print("\nFirst 5 rows of the company-specific headlines with sentiment scores:")
display(df_company_headlines_sentiment.head())

print("\nInfo of the company-specific headlines with sentiment scores:")
df_company_headlines_sentiment.info()

First 5 rows of the company-specific headlines with sentiment scores:

,ticker,News_Title,date,eventRet,Close,Title_Sentiment
0,AMZN,Whole Foods (WFMI) -5.2% following a downgrade...,2011-05-02,0.017650,10.059500,-0.65
1,NFLX,Netflix (NFLX +1.1%) shares post early gains a...,2011-05-02,-0.012912,33.884285,-0.64
2,MSFT,The likely winners in Microsoft's (MSFT -1.4%)...,2011-05-10,-0.019817,20.120024,-0.70
3,MSFT,Microsoft (MSFT -1.2%) and Skype signed their ...,2011-05-10,-0.019817,20.120024,0.00
4,MSFT,NaN,2011-05-10,-0.019817,20.120024,0.00

Info of the company-specific headlines with sentiment scores:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2768 entries, 0 to 2767
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ticker           2768 non-null   object
 1   News_Title       2759 non-null   object
 2   date             2768 non-null   datetime64[ns]
 3   eventRet         2768 non-null   float64
 4   Close            2768 non-null   float64
 5   Title_Sentiment  2768 non-null   float64
dtypes: datetime64[ns](1), float64(3), object(2)
memory usage: 129.9+ KB

### Creating the Combined Dataset: Merging Historical Stock Data with Company-Specific Weekly Sentiment

### Exporting the Combined Dataset

In [ ]:
from google.colab import files

output_file_name = 'combined_stock_data_with_sentiment.csv'

try:
    combined_dataset.to_csv(output_file_name, index=False)
    print(f"Successfully saved '{output_file_name}'")
    files.download(output_file_name)
    print(f"Downloading {output_file_name}...")
except Exception as e:
    print(f"Could not save or download {output_file_name}: {e}")

Successfully saved 'combined_stock_data_with_sentiment.csv'

Downloading combined_stock_data_with_sentiment.csv...

In [ ]:
display(combined_dataset.head())

        Date  Open  High   Low Close Volume Ticker  Title_Sentiment
0 2006-04-10  <NA>  <NA>  <NA>  <NA>   <NA>   NVDA              NaN
1 2006-04-17  <NA>  <NA>  <NA>  <NA>   <NA>   NVDA              NaN
2 2006-04-24  <NA>  <NA>  <NA>  <NA>   <NA>   NVDA              NaN
3 2006-05-01  <NA>  <NA>  <NA>  <NA>   <NA>   NVDA              NaN
4 2006-05-08  <NA>  <NA>  <NA>  <NA>   <NA>   NVDA              NaN

In [ ]:
import pandas as pd
import yfinance as yf
from datetime import datetime, timedelta
import requests

# --- Re-execute preliminary steps to ensure variables are defined ---
# From cell 47bb281c: Get S&P 500 table
url = 'https://en.wikipedia.org/wiki/List_of_S%26P_500_companies'
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'}
response = requests.get(url, headers=headers)
tables = pd.read_html(response.text)
sp500_table = tables[0]

# From cell e1727944: Get top 50 S%26P 500 tickers by market cap
ticker_market_caps = []
for symbol in sp500_table['Symbol']:
    ticker = yf.Ticker(symbol)
    try:
        market_cap = ticker.info.get('marketCap', 0)
    except Exception:
        market_cap = 0
    ticker_market_caps.append({'Symbol': symbol, 'MarketCap': market_cap})
market_cap_df = pd.DataFrame(ticker_market_caps)
market_cap_df = market_cap_df.sort_values(by='MarketCap', ascending=False)
top_50_sp500_tickers_by_market_cap = market_cap_df.head(50)['Symbol'].tolist()

# From cell 79e370bc: Define date range
end_date = datetime.now()
start_date = end_date - timedelta(days=20 * 365) # Approximation for 20 years

# --- Re-populate historical_data ---
historical_data = {}
for ticker_symbol in top_50_sp500_tickers_by_market_cap:
    try:
        data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk', progress=False)
        if not data.empty:
            # Flatten columns if they are a MultiIndex
            if isinstance(data.columns, pd.MultiIndex):
                # This explicitly handles cases where the MultiIndex has different levels.
                # It tries to find the 'base' column names (Open, High, etc.)
                # and if not possible, it will create unique names.
                new_cols = []
                for col_name in data.columns:
                    if isinstance(col_name, tuple):
                        # Take the last element of the tuple if it's not empty, otherwise the first
                        new_col = col_name[-1] if col_name[-1] else col_name[0]
                        new_cols.append(new_col)
                    else:
                        new_cols.append(col_name)
                data.columns = new_cols

            # Standardize column names: rename 'Adj Close' to 'Close' if present
            if 'Adj Close' in data.columns:
                data = data.rename(columns={'Adj Close': 'Close'})

            # Ensure only standard columns exist and in a specific order
            required_cols = ['Date', 'Open', 'High', 'Low', 'Close', 'Volume']
            # Get 'Date' from index and rename explicitly
            data = data.reset_index()
            data = data.rename(columns={'index': 'Date'}) # yfinance uses 'Date' as index name

            # Filter and reorder columns
            # Ensure all required_cols are present, add missing ones with NaN
            for col in required_cols:
                if col not in data.columns:
                    data[col] = pd.NA

            data = data[required_cols] # Select and reorder

            data['Ticker'] = ticker_symbol
            # Drop duplicates if any, keeping the last one (for robustness)
            data = data.drop_duplicates(subset=['Date', 'Ticker'], keep='last')

            historical_data[ticker_symbol] = data
    except Exception as e:
        print(f"Error processing {ticker_symbol}: {e}")

# Concatenate all DataFrames into a single DataFrame
all_dfs_for_concat = list(historical_data.values())
if all_dfs_for_concat:
    consolidated_df = pd.concat(all_dfs_for_concat, ignore_index=True)
else:
    consolidated_df = pd.DataFrame() # Handle case where no data is downloaded

# consolidated_stock_df_final is now the consolidated_df after cleaning
consolidated_stock_df_final = consolidated_df.copy()

# Ensure 'Date' column is datetime type for merging
consolidated_stock_df_final['Date'] = pd.to_datetime(consolidated_stock_df_final['Date'])

# --- Step 2: Aggregate df_company_headlines_sentiment to weekly sentiment ---
# Ensure df_company_headlines_sentiment is defined and up-to-date. (created in cell 58fc36ba)
# Make sure 'date' column is datetime type
df_company_headlines_sentiment['date'] = pd.to_datetime(df_company_headlines_sentiment['date'])

# Function to get the week-ending date (Friday)
def get_week_ending_date(date):
    # Friday is weekday 4. pd.Timedelta handles negative days correctly for previous week
    days_until_friday = (4 - date.weekday() + 7) % 7
    return date + pd.Timedelta(days=days_until_friday)

df_company_headlines_sentiment['Week_End_Date'] = df_company_headlines_sentiment['date'].apply(get_week_ending_date)

# Aggregate sentiment to weekly mean
weekly_sentiment = df_company_headlines_sentiment.groupby(['ticker', 'Week_End_Date'])['Title_Sentiment'].mean().reset_index()
weekly_sentiment = weekly_sentiment.rename(columns={'ticker': 'Ticker', 'Week_End_Date': 'Date'})

# --- Step 3: Merge the two prepared DataFrames ---
combined_dataset = pd.merge(consolidated_stock_df_final, weekly_sentiment, on=['Date', 'Ticker'], how='left')

print("First 5 rows of the combined dataset:")
display(combined_dataset.head())

print("\nInfo of the combined dataset:")
combined_dataset.info()

/tmp/ipykernel_961/3917572233.py:11: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(response.text)
/tmp/ipykernel_961/3917572233.py:35: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk', progress=False)
/tmp/ipykernel_961/3917572233.py:35: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk', progress=False)
/tmp/ipykernel_961/3917572233.py:35: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk', progress=False)
/tmp/ipykernel_961/3917572233.py:35: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk', progress=False)
/tmp/ipykernel_961/3917572233.py:35: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk', progress=False)
/tmp/ipykernel_961/3917572233.py:35: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk', progress=False)
/tmp/ipykernel_961/3917572233.py:35: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk', progress=False)
/tmp/ipykernel_961/3917572233.py:35: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk', progress=False)
/tmp/ipykernel_961/3917572233.py:35: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk', progress=False)
/tmp/ipykernel_961/3917572233.py:35: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk', progress=False)
/tmp/ipykernel_961/3917572233.py:35: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk', progress=False)
/tmp/ipykernel_961/3917572233.py:35: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk', progress=False)
/tmp/ipykernel_961/3917572233.py:35: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk', progress=False)
/tmp/ipykernel_961/3917572233.py:35: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk', progress=False)
/tmp/ipykernel_961/3917572233.py:35: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk', progress=False)
/tmp/ipykernel_961/3917572233.py:35: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk', progress=False)
/tmp/ipykernel_961/3917572233.py:35: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk', progress=False)
/tmp/ipykernel_961/3917572233.py:35: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk', progress=False)
/tmp/ipykernel_961/3917572233.py:35: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk', progress=False)
/tmp/ipykernel_961/3917572233.py:35: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk', progress=False)
/tmp/ipykernel_961/3917572233.py:35: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk', progress=False)
/tmp/ipykernel_961/3917572233.py:35: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk', progress=False)
/tmp/ipykernel_961/3917572233.py:35: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk', progress=False)
/tmp/ipykernel_961/3917572233.py:35: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk', progress=False)
/tmp/ipykernel_961/3917572233.py:35: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk', progress=False)
/tmp/ipykernel_961/3917572233.py:35: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk', progress=False)
/tmp/ipykernel_961/3917572233.py:35: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk', progress=False)
/tmp/ipykernel_961/3917572233.py:35: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk', progress=False)
/tmp/ipykernel_961/3917572233.py:35: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk', progress=False)
/tmp/ipykernel_961/3917572233.py:35: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk', progress=False)
/tmp/ipykernel_961/3917572233.py:35: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk', progress=False)
/tmp/ipykernel_961/3917572233.py:35: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk', progress=False)
/tmp/ipykernel_961/3917572233.py:35: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk', progress=False)
/tmp/ipykernel_961/3917572233.py:35: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk', progress=False)
/tmp/ipykernel_961/3917572233.py:35: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk', progress=False)
/tmp/ipykernel_961/3917572233.py:35: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk', progress=False)
/tmp/ipykernel_961/3917572233.py:35: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk', progress=False)
/tmp/ipykernel_961/3917572233.py:35: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk', progress=False)
/tmp/ipykernel_961/3917572233.py:35: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk', progress=False)
/tmp/ipykernel_961/3917572233.py:35: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk', progress=False)
/tmp/ipykernel_961/3917572233.py:35: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk', progress=False)
/tmp/ipykernel_961/3917572233.py:35: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk', progress=False)
/tmp/ipykernel_961/3917572233.py:35: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk', progress=False)
/tmp/ipykernel_961/3917572233.py:35: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk', progress=False)
/tmp/ipykernel_961/3917572233.py:35: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk', progress=False)
/tmp/ipykernel_961/3917572233.py:35: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk', progress=False)
/tmp/ipykernel_961/3917572233.py:35: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk', progress=False)
/tmp/ipykernel_961/3917572233.py:35: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk', progress=False)
/tmp/ipykernel_961/3917572233.py:35: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk', progress=False)
/tmp/ipykernel_961/3917572233.py:35: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1wk', progress=False)

First 5 rows of the combined dataset:

        Date  Open  High   Low Close Volume Ticker  Title_Sentiment
0 2006-04-10  <NA>  <NA>  <NA>  <NA>   <NA>   NVDA              NaN
1 2006-04-17  <NA>  <NA>  <NA>  <NA>   <NA>   NVDA              NaN
2 2006-04-24  <NA>  <NA>  <NA>  <NA>   <NA>   NVDA              NaN
3 2006-05-01  <NA>  <NA>  <NA>  <NA>   <NA>   NVDA              NaN
4 2006-05-08  <NA>  <NA>  <NA>  <NA>   <NA>   NVDA              NaN

Info of the combined dataset:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49184 entries, 0 to 49183
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Date             49184 non-null  datetime64[ns]
 1   Open             0 non-null      object
 2   High             0 non-null      object
 3   Low              0 non-null      object
 4   Close            0 non-null      object
 5   Volume           0 non-null      object
 6   Ticker           49184 non-null  object
 7   Title_Sentiment  0 non-null      float64
dtypes: datetime64[ns](1), float64(1), object(6)
memory usage: 3.0+ MB